version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-importer-app
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    environment:
      - ENV=production
      - PORT=3000